### ISSUE TITLE
일주일 지난 PR은 그냥 머지 시키고 PR 리스트에서 없애버리자.

### ISSUE THREAD

**Issue by seacloud15** [leon1114/scsa_lc_study#109]
일주일 지난 PR은 그냥 머지 시키고 PR 리스트에서 없애버리자.
너무 옛날거는 리뷰 봐도 무슨 문제였는지 기억도 안나고 내가 리뷰 했는지 안했는지도 헷갈림 ㅋㅋ

**Comment by leon1114** [comment]
오 굿 그럼 내가 문제 업데이트하면서 1주일 지난 것들은 강제 병합 하겠음

**Comment by leon1114** [comment]
적용 완료
